defmodule ExLokaliseTransfer.Downloader.Bundle.SafetyTest do
  use ExLokaliseTransfer.Case, async: true

  alias ExLokaliseTransfer.Downloader.Bundle.Safety

  describe "validate_zip_entries/1" do
    test "returns :ok for safe binary file names" do
      entries = [
        {:zip_file, "en.json", :file_info, [], 0, 10},
        {:zip_file, "translations/lv/common.json", :file_info, [], 10, 20}
      ]

      assert :ok = Safety.validate_zip_entries(entries)
    end

    test "returns :ok for safe charlist file names" do
      entries = [
        {:zip_file, ~c"en.json", :file_info, [], 0, 10},
        {:zip_file, ~c"translations/lv/common.json", :file_info, [], 10, 20}
      ]

      assert :ok = Safety.validate_zip_entries(entries)
    end

    test "returns :ok for plain binary names" do
      entries = [
        "en.json",
        "translations/lv/common.json"
      ]

      assert :ok = Safety.validate_zip_entries(entries)
    end

    test "returns :ok for plain charlist names" do
      entries = [
        ~c"en.json",
        ~c"translations/lv/common.json"
      ]

      assert :ok = Safety.validate_zip_entries(entries)
    end

    test "skips zip comments" do
      entries = [
        {:zip_comment, ~c"generated by test"},
        {:zip_file, "translations/en.json", :file_info, [], 0, 10}
      ]

      assert :ok = Safety.validate_zip_entries(entries)
    end

    test "returns error for parent directory traversal in binary zip entry name" do
      entries = [
        {:zip_file, "../evil.txt", :file_info, [], 0, 10}
      ]

      assert {:error, {:unsafe_zip_entry, "../evil.txt"}} =
               Safety.validate_zip_entries(entries)
    end

    test "returns error for parent directory traversal in charlist zip entry name" do
      entries = [
        {:zip_file, ~c"../evil.txt", :file_info, [], 0, 10}
      ]

      assert {:error, {:unsafe_zip_entry, "../evil.txt"}} =
               Safety.validate_zip_entries(entries)
    end

    test "returns error for nested parent traversal" do
      entries = [
        {:zip_file, "translations/../../evil.txt", :file_info, [], 0, 10}
      ]

      assert {:error, {:unsafe_zip_entry, "translations/../../evil.txt"}} =
               Safety.validate_zip_entries(entries)
    end

    test "returns error for unix absolute paths" do
      entries = [
        {:zip_file, "/etc/passwd", :file_info, [], 0, 10}
      ]

      assert {:error, {:unsafe_zip_entry, "/etc/passwd"}} =
               Safety.validate_zip_entries(entries)
    end

    test "returns error for windows absolute paths with backslashes" do
      entries = [
        {:zip_file, "C:\\temp\\evil.txt", :file_info, [], 0, 10}
      ]

      assert {:error, {:unsafe_zip_entry, "C:\\temp\\evil.txt"}} =
               Safety.validate_zip_entries(entries)
    end

    test "returns error for windows traversal paths with backslashes" do
      entries = [
        {:zip_file, "..\\..\\evil.txt", :file_info, [], 0, 10}
      ]

      assert {:error, {:unsafe_zip_entry, "..\\..\\evil.txt"}} =
               Safety.validate_zip_entries(entries)
    end

    test "returns error for first unsafe entry and stops scanning" do
      entries = [
        {:zip_file, "ok/en.json", :file_info, [], 0, 10},
        {:zip_file, "../evil.txt", :file_info, [], 10, 20},
        {:zip_file, "/also/bad.txt", :file_info, [], 20, 30}
      ]

      assert {:error, {:unsafe_zip_entry, "../evil.txt"}} =
               Safety.validate_zip_entries(entries)
    end

    test "returns error for invalid zip entry structure" do
      entries = [
        {:unexpected, "en.json"}
      ]

      assert {:error, {:invalid_zip_entry, {:unexpected, "en.json"}}} =
               Safety.validate_zip_entries(entries)
    end

    test "returns error for non-string-like entry" do
      entries = [
        123
      ]

      assert {:error, {:invalid_zip_entry, 123}} =
               Safety.validate_zip_entries(entries)
    end

    test "accepts relative names containing dots but not dot-dot segments" do
      entries = [
        {:zip_file, "./translations/en.json", :file_info, [], 0, 10},
        {:zip_file, "messages.v1.json", :file_info, [], 10, 20}
      ]

      assert :ok = Safety.validate_zip_entries(entries)
    end
  end
end
